### PR TITLE
Simple improvement to `Rope::lines()` iterator by adding a cache

### PR DESCRIPTION
**Pull request by poliorcetics**
- fix: small clippy lints that don't affect public API
- nit: improve TextInfo Add|SubAssign impls
- feat: cache progression in the `Lines` iterator, making around 30% faster

### CODE REVIEW

**Comment by poliorcetics** [comment]
@pascalkuthe here are my first changes, the one I'm sure about. I'm exploring improvements to the underlying methods, but this PR alone is a 34% improvement.

### Benchmarking

I created files with line breaks at line 100, with 10k lines, 100k lines and 1 million line.

Before this PR, on my machine, it took

```
ropey-10k.txt => 10001 lines, 6.6705ms
ropey-100k.txt => 100001 lines, 67.236666ms
ropey-1m.txt => 1000001 lines, 681.34475ms
```

Now it takes:

```
ropey-10k.txt => 10001 lines, 4.445ms
ropey-100k.txt => 100001 lines, 44.790708ms
ropey-1m.txt => 1000001 lines, 454.385208ms
```

Code used for tests:

```
extern crate ropey;

use std::fs::File;
use std::io::BufReader;

use ropey::Rope;

fn main() {
    mesure("10k");
    mesure("100k");
    mesure("1m");
}

fn mesure(f: &str) {
    let text = Rope::from_reader(BufReader::new(File::open(format!("/tmp/ropey-{f}.txt")).unwrap())).unwrap();

    let start = std::time::Instant::now();
    let count = text.lines().count();
    let end = start.elapsed();
    println!("ropey-{f}.txt => {count} lines, {end:?}");
}
```

I'm not uploading the files because they're very heavy, but I can probably put them on some random hosting service if needed

**Comment by archseer** [comment]
Could you store a `chunk_iter: Chunks<'a>` similar to how `Bytes` and `Chars` do? It seems like LinesEnum is doing a similar job

**Comment by pascalkuthe** [comment]
Thanks for posting this. This version offers a nice speesbump but there is still lots of performance left on the table. This  version performs multiple binary searches (get_chunk_at_lines, RopeSlice::new). 

As @archseer mentioned we ideally want to simply iterate all chunks with the `Chunks` iterator and construct the line slices during that transversal. However then you are still calling `RopeSlice::new`. To avoid that, I have implemented a custom version of the chunks iterator that tracks the lowest common ancestor of a line. I wanted to post a PR last week but reverse iteration still base some bugs and private things got in the way. Will try to post my version as a draft later today or latest tomorrow

**Comment by pascalkuthe** [comment]
I posted #70. Multiple tests still fail on that branch it contains some unrelated changes. I just posted it to showoff my approach

**Comment by cessen** [comment]
@poliorcetics 

I definitely appreciate the effort you've put into this!  Unfortunately @pascalkuthe's PR (#70) is really the approach I had in mind.  So I'm closing this in favor of that.  Sorry about that!

**Comment by poliorcetics** [comment]
Don't worry, their solution is best yes, mine was more of a stopgap :)

**Pull request closed without merging**
